### ISSUE TITLE
Missing scaffolding.less

### ISSUE THREAD

**Issue by robhicks** [caitp/bootstrapless#1]
The project is missing scaffolding.less

**Comment by caitp** [comment]
V3 of this repo is pretty buggy, I would direct you to [strapless](https://github.com/caitp/strapless)

I had set this up as a mirror of strapless, because it seems like an easier-to-search name, but it's kind of a pain picking up after both of them. When the next official release is updated, this one will be fixed up --- but for now [strapless](https://github.com/caitp/strapless) is the way to go

**Comment by caitp** [comment]
Not to ping you, but if anyone is reading this in the future, with the release of v3.0.1 this mirror of [strapless](http://github.com/caitp/strapless) is synchronized and has the bugfixes which were added to the other repository. So, this one shouldn't be missing anything, that I can tell.

If anyone wants to write a test suite for the gruntfile, that would be pretty cool!
